services:
  web:
    build: .
    container_name: autocomplete_api
    restart: always
    ports:
      - "8019:8019"
    environment:
      - DATABASE_URL=postgresql://gbuser:aidev123@217.217.249.121:5432/auto_complete